name: Manual workflow

on:
    workflow_dispatch:

permissions:
    id-token: write # This is required for requesting the JWT

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: Infisical/secrets-action@v1.0.7
            with:
                method: "oidc"
                env-slug: "dev"
                project-slug: "nxlab-hail"
                identity-id: "23044567-b3d4-46de-a2f9-8d8670ab041f"
